### ISSUE TITLE
todo spring 2024

### ISSUE THREAD

**Issue by mluukkai** [ohtuprojekti-ilmo/ohtuilmo-backend#139]
- [ ] kesälle mahdollisuus merkata ajankohtatoive (asiakas, opiskelija)
- [ ] järjestäminen uusin -> vanhin
- [ ] adminille parempi menu (kaikki menuun)
- [ ] dev setup
- [ ] arvostelujen katselufeature paremmaksi
- [ ] ohjaajille näkyvyys asiakkaan arvioihin 
- [ ] mahdollisuus nähdä edellisten lukukausien toteutuneet projektit
- [ ] valitun ryhmän näyttö opiskelijalle, mahdollisuus tehdä viesti joka näytetään valitulle ryhmälle
- [ ] ilmottautumisesta sähköpostitse vahvistus
